WIP

diff --git a/dtk b/dtk
--- a/dtk
+++ b/dtk
@@ -3,23 +3,18 @@
 set -e
 
 long_opts=help,host-network-interface:,host-only-network:,vboxdir:,check-compatibility,create-template,networking:,\
-monitoring:,storage:,single-node,up:,down:,delete:,verify:,sshto:,template-name:,linux:,containerized-cplane:
+monitoring:,storage:,single-node,up:,down:,delete:,verify:,template-name:,linux:,containerized-cplane:
 
 # api
 host_network_interface=
 host_only_network=
 vboxdir=
-check_compatibility=0
 create_template=0
 networking=
 monitoring=
 storage=
 single_node=0
-up=
-down=
-delete=
 verify=
-sshto=
 template_name=bingo
 linux=centos8
 containerized_cplane=
@@ -40,77 +35,6 @@ set -a
 source $DTKBASE/artifacts
 set +a
 
-#
-# Verifies the existence of all the possible filesystem objects required to provision a cluster.
-#
-function check_files() {
-  for f in $ALMA_ISO_FILE\
-    $CALICO_CUSTOM_RESOURCES_MANIFEST\
-    $CALICO_TIGERA_MANIFEST\
-    $CENTOS8_ISO_FILE\
-    $CENTOS9_ISO_FILE\
-    $CNI_PLUGINS_BINARY\
-    $CONTAINERD_BINARY\
-    $CRICTL_BINARY\
-    $ETCD_GZIP\
-    $GUEST_ADDITIONS_ISO_FILE\
-    $KUBE_APISERVER_BINARY\
-    $KUBE_CONTROLLER_MANAGER_BINARY\
-    $KUBELET_BINARY\
-    $KUBE_PROMETHEUS_BINARY\
-    $KUBE_PROXY_BINARY\
-    $KUBERNETES_DASHBOARD_MANIFEST\
-    $KUBE_SCHEDULER_BINARY\
-    $METRICS_SERVER_MANIFEST\
-    $OPENEBS_HOSTPATH_OPERATOR_MANIFEST\
-    $OPENEBS_SC_MANIFEST\
-    $ROCKY_ISO_FILE\
-    $RUNC_BINARY;
-    do
-      if ! [[ -f $f ]]; then
-        echo "missing: $f" >&2
-        result=1
-      else
-        echo "OK: $f"
-      fi
-    done
-}
-
-#
-# Verifies the existence of all possible downloads required to provision a cluster.
-#
-function check_urls() {
-  for f in $ALMA_ISO_DOWNLOAD\
-    $CALICO_CUSTOM_RESOURCES_DOWNLOAD\
-    $CALICO_TIGERA_DOWNLOAD\
-    $CENTOS8_ISO_DOWNLOAD\
-    $CENTOS9_ISO_DOWNLOAD\
-    $CNI_PLUGINS_DOWNLOAD\
-    $CONTAINERD_DOWNLOAD\
-    $CRICTL_DOWNLOAD\
-    $ETCD_DOWNLOAD\
-    $GUEST_ADDITIONS_ISO_DOWNLOAD\
-    $KUBE_APISERVER_DOWNLOAD\
-    $KUBE_CONTROLLER_MANAGER_DOWNLOAD\
-    $KUBELET_DOWNLOAD\
-    $KUBE_PROMETHEUS_DOWNLOAD\
-    $KUBE_PROXY_DOWNLOAD\
-    $KUBERNETES_DASHBOARD_DOWNLOAD\
-    $KUBE_SCHEDULER_DOWNLOAD\
-    $METRICS_SERVER_DOWNLOAD\
-    $OPENEBS_HOSTPATH_OPERATOR_MANIFEST_DOWNLOAD\
-    $OPENEBS_SC_MANIFEST_DOWNLOAD\
-    $ROCKY_ISO_DOWNLOAD\
-    $RUNC_DOWNLOAD;
-    do
-      if ! curl -sL $f -o /dev/null --head --fail; then
-        echo "missing: $f" >&2
-        result=1
-      else
-        echo "OK: $f"
-      fi
-    done
-}
 
 #
 # option parsing helper
@@ -125,7 +49,8 @@ function opt_val() {
 }
 
 #
-# parses command line parameters and sets script variables from them
+# parses command line parameters and sets script variables from them, executes helper
+# commands, like --up for example.
 #
 function parse_args() {
   if [[ "$#" -eq 0 ]]; then
@@ -163,8 +88,9 @@ function parse_args() {
         shift 2
         ;;
       --check-compatibility)
-        check_compatibility=1
-        shift
+        echo "Checking version compatibility"
+        xec check-compatibility
+        exit 0
         ;;
       --create-template)
         create_template=1
@@ -195,16 +121,19 @@ function parse_args() {
         shift
         ;;
       --up)
-        up=$(opt_val "$2")
-        shift 2
+        vms=$(opt_val "$2")
+        xec up-down-del "up" $vms
+        exit 0
         ;;
       --down)
-        down=$(opt_val "$2")
-        shift 2
+        vms=$(opt_val "$2")
+        xec up-down-del "down" $vms
+        exit 0
         ;;
       --delete)
-        delete=$(opt_val "$2")
-        shift 2
+        vms=$(opt_val "$2")
+        xec up-down-del "delete" $vms
+        exit 0
         ;;
       --verify)
         verify=$(opt_val "$2")
@@ -212,11 +141,8 @@ function parse_args() {
           echo "unsupported parameter value for --verify option: $verify"
           exit 1
         fi
-        shift 2
-        ;;
-      --sshto)
-        sshto=$(opt_val "$2")
-        shift 2
+        xec check-objects "$verify"
+        exit 0
         ;;
       --template-name)
         template_name=$(opt_val "$2")
@@ -241,69 +167,44 @@ function parse_args() {
     echo "Unsupported command line option(s): $@"
     exit 1
   fi
+
+  if [[ -z "$host_network_interface" ]] && [[ -z "$host_only_network" ]]; then
+    echo "either --host-network-interface or --host-only-network is required"
+    exit 1
+  elif [[ ! -z "$host_network_interface" ]] && [[ ! -z "$host_only_network" ]]; then
+    echo "--host-network-interface and --host-only-network are exclusive of each other"
+    exit 1
+  elif [[ -z "$vboxdir" ]]; then
+    echo "--vboxdir is a required option"
+    exit 1
+  elif [[ ! -d $vboxdir ]]; then
+    echo "directory for virtualbox VMs does not exist: $vboxdir"
+    exit 1
+  fi
 }
 
 # entry point
 
 parse_args "$@"
 
-if [[ $check_compatibility -eq 1 ]]; then
-  echo "Checking version compatibility"
-  xec verify-prereqs
-  exit 0
-elif [[ "$verify" == "upstreams" ]]; then
-  check_urls
-  exit 0
-elif [[ "$verify" == "files" ]]; then
-  check_files
-  exit 0
-elif [[ ! -z "$up" ]]; then
-  IFS=',' read -ra vms <<< "$up"
-  for vm in "${vms[@]}"; do
-    VBoxManage startvm $vm
-  done
-  xec show-ssh $DTKBASE/generated/kickstart/id_ed25519 "${vms[@]}"
-  exit 0
-elif [[ ! -z "$down" ]]; then
-  IFS=',' read -ra vms <<< "$down"
-  for vm in "${vms[@]}"; do
-    echo "shutting down $vm"
-    VBoxManage controlvm $vm acpipowerbutton
-    xec wait-vm $vm --stopped
-  done
-  exit 0
-elif [[ ! -z "$delete" ]]; then
-  IFS=',' read -ra vms <<< "$delete"
-  for vm in "${vms[@]}"; do
-    echo "shutting down $vm if running"
-    VBoxManage controlvm $vm poweroff &>/dev/null && xec wait-vm $vm --stopped || echo "(not running)"
-    echo "removing $vm"
-    sleep 2s
-    VBoxManage unregistervm $vm --delete
-  done
-  exit 0
-elif [[ ! -z "$sshto" ]]; then
-  ip=$(xec get-vm-ip $sshto)
-  ssh -i $DTKBASE/generated/kickstart/id_ed25519 root@$ip
-fi
-
-if [[ -z "$host_network_interface" ]] && [[ -z "$host_only_network" ]]; then
-  echo "either --host-network-interface or --host-only-network is required"
-  exit 1
-elif [[ ! -z "$host_network_interface" ]] && [[ ! -z "$host_only_network" ]]; then
-  echo "--host-network-interface and --host-only-network are exclusive of each other"
-  exit 1
-elif [[ -z "$vboxdir" ]]; then
-  echo "--vboxdir is a required option"
-  exit 1
-elif [[ ! -d $vboxdir ]]; then
-  echo "directory for virtualbox VMs does not exist: $vboxdir"
-  exit 1
-fi
-
 # create directories to generate various files into
-mkdir -p $DTKBASE/generated/kickstart $DTKBASE/generated/kubeconfig\
-         $DTKBASE/generated/cert $DTKBASE/generated/hostonly-netcfg $DTKBASE/generated/iso
+mkdir -p $DTKBASE/generated/kickstart\
+         $DTKBASE/generated/kubeconfig\
+         $DTKBASE/generated/cert\
+         $DTKBASE/generated/hostonly-netcfg\
+         $DTKBASE/generated/iso
+
+# TEST TEST TEST
+
+xec download-objects\
+  --create-template=$create_template\
+  --linux=$linux\
+  --monitoring=$monitoring\
+  --storage=$storage\
+  --networking=$networking\
+  --kubernetes-dashboard=true
+
+exit 0
 
 # Create a template VM to clone the nodes from. This step also generates the SSH keys into the 'generated/kickstart'
 # directory that are used all over the place to interact with the node VMs via ssh/scp as they are being bootstrapped,
