Kubernetes 1.24.2, crictl 1.24.2, cni plugins 1.1.1, calico 3.23.2

diff --git a/networking/calico/install-calico-networking b/networking/calico/install-calico-networking
--- a/networking/calico/install-calico-networking
+++ b/networking/calico/install-calico-networking
@@ -2,12 +2,12 @@
 
 set -e
 
-long_opts=calico-manifest-download:,calico-manifest:,priv-key:,admin-kubeconfig:,pod-cidr:,nodes:
+long_opts=calico-download:,calico-binary:,priv-key:,admin-kubeconfig:,pod-cidr:,nodes:
 script_name=$(basename "$0")
 proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
 
-calico_manifest_download=
-calico_manifest=
+calico_download=
+calico_binary=
 priv_key=
 admin_kubeconfig=
 pod_cidr=
@@ -32,12 +32,12 @@ function parse_args() {
   eval set -- "$parsed"
   while true; do
     case "$1" in
-      --calico-manifest-download)
-        calico_manifest_download=$(opt_val "$2")
+      --calico-download)
+        calico_download=$(opt_val "$2")
         shift 2
         ;;
-      --calico-manifest)
-        calico_manifest=$(opt_val "$2")
+      --calico-binary)
+        calico_binary=$(opt_val "$2")
         shift 2
         ;;
       --priv-key)
@@ -67,32 +67,58 @@ function parse_args() {
 
 parse_args "$@"
 
-calico_manifest_actual=$($proj_root/scripts/make-download-path\
- --download-url=$calico_manifest_download --download-path=$calico_manifest)
+calico_binary_actual=$($proj_root/scripts/make-download-path\
+ --download-url=$calico_download --download-path=$calico_binary)
+
+# parse the calico version because it is embedded in a path in the TGZ that contains the manifest we want
+calico_version=
+regex="calico-(v[0-9]{,2}\.[0-9]{,2}\.[0-9]{,2})\.tgz"
+if [[ $calico_binary =~ $regex ]]; then
+  # e.g. 'v3.23.2'
+  calico_version="${BASH_REMATCH[1]}"
+else
+  echo "unable to parse a version number in the expected form from the calico binary: $calico_binary_actual"
+  exit 1
+fi
 
 # debug
-#echo "calico_manifest_download=$calico_manifest_download"
-#echo "calico_manifest=$calico_manifest"
-#echo "calico_manifest_actual=$calico_manifest_actual"
-#echo "priv_key=$priv_key"
-#echo "admin_kubeconfig=$admin_kubeconfig"
-#echo "pod_cidr=$pod_cidr"
-#echo "nodes=${nodes[@]}"
+# echo "calico_download=$calico_download"
+# echo "calico_binary=$calico_binary"
+# echo "calico_binary_actual=$calico_binary_actual"
+# echo "calico_version=$calico_version"
+# echo "priv_key=$priv_key"
+# echo "admin_kubeconfig=$admin_kubeconfig"
+# echo "pod_cidr=$pod_cidr"
+# echo "nodes=${nodes[@]}"
 
 ## per https://docs.projectcalico.org/maintenance/troubleshoot/troubleshooting#configure-networkmanager
+## last eyeballed on 14-Jul-2022
 for node in "${nodes[@]}"; do
   worker_ip=$($proj_root/scripts/get-vm-ip $node)
   ssh -i $priv_key root@$worker_ip << EOF
-    echo -e "[keyfile]\nunmanaged-devices=interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico"\
+    echo -e "[keyfile]\unmanaged-devices=interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico;interface-name:wireguard.cali"\
       >| /etc/NetworkManager/conf.d/calico.conf
     systemctl daemon-reload && systemctl restart NetworkManager
 EOF
 done
 
-$proj_root/scripts/download-obj --url="$calico_manifest_download" --dest="$calico_manifest_actual"
+# only download the tgz if we don't already have the versioned manifest
+if [[ ! -f $proj_root/binaries/calico-$calico_version.yaml ]]; then
+  $proj_root/scripts/download-obj --url="$calico_download" --dest="$calico_binary_actual"
+fi
+
+# ditto extract
+if [[ ! -f $proj_root/binaries/calico-$calico_version.yaml ]]; then
+  echo "extracting calico manifest from tgz"
+  tar zxvf $calico_binary_actual\
+    --strip-components 2\
+    -C $proj_root/binaries\
+    --transform "s/calico.yaml/calico-$calico_version.yaml/g"\
+    release-$calico_version/manifests/calico.yaml
+fi
 
 echo "deploying calico manifest"
-kubectl --kubeconfig $admin_kubeconfig create -f $calico_manifest_actual
+kubectl --kubeconfig $admin_kubeconfig create -f $proj_root/binaries/calico-$calico_version.yaml
 kubectl --kubeconfig $admin_kubeconfig -n kube-system set env ds/calico-node CALICO_IPV4POOL_CIDR=$pod_cidr
 
 echo "waiting (indefinitely) for calico daemonset"
