host-only install bug, messaging improvement

diff --git a/scripts/create-hostonly-network b/scripts/create-hostonly-network
--- a/scripts/create-hostonly-network
+++ b/scripts/create-hostonly-network
@@ -1,4 +1,3 @@
-
 #!/usr/bin/env bash
 
 #
@@ -16,12 +15,12 @@
 set -e
 
 if [[ "$#" -ne 1 ]]; then
-  echo "usage: create-hostonly-network <network-octets>"
+  1>&2 echo "usage: create-hostonly-network <network-octets>"
   exit 1
 fi
 
 if VBoxManage list hostonlyifs | grep IPAddress | awk '{print $2}' | grep -q $1; then
-  echo "error: a host only network already exists for network $1"
+  1>&2 echo "error: a host only network already exists for network $1"
   exit 1
 fi
 
