Completed controller install

diff --git a/newroot/scripts/configure-controller b/newroot/scripts/configure-controller
--- a/newroot/scripts/configure-controller
+++ b/newroot/scripts/configure-controller
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
-# expects 'clone-vm' to have been run first so that the controller VM is initialized and available
+# expects 'create-controller' to have been run first so that the controller VM is initialized and available
 # todo don't pass kubernetes_cert/key since this generates them
-# todo don't pass template-vmname since this doesn;t do the clone
+# todo don't pass template-vmname since this doesn't do the clone
 # todo consider --no-gen-cluster-certs
 
 set -e
@@ -10,6 +10,7 @@ set -e
 long_opts=template-vmname:,controller-hostname:,controller-ram:,controller-cpus:,vboxdir:,priv-key:,\
 etcd-download:,etcd-gzip:,kube-apiserver-download:,kube-apiserver-binary:,\
 kube-controller-manager-download:,kube-controller-manager-binary:,\
+kube-scheduler-download:,kube-scheduler-binary:,\
 kubernetes-cert:,kubernetes-key:,\
 ca-cert:,ca-key:
 script_name=$(basename "$0")
@@ -28,6 +29,8 @@ kube_apiserver_download=
 kube_apiserver_binary=
 kube_controller_manager_download=
 kube_controller_manager_binary=
+kube_scheduler_download=
+kube_scheduler_binary=
 kubernetes_cert=
 kubernetes_key=
 ca_cert=
@@ -103,6 +106,14 @@ function parse_args() {
         kube_controller_manager_binary=$(opt_val "$2")
         shift 2
         ;;
+      --kube-scheduler-download)
+        kube_scheduler_download=$(opt_val "$2")
+        shift 2
+        ;;
+      --kube-scheduler-binary)
+        kube_scheduler_binary=$(opt_val "$2")
+        shift 2
+        ;;
       --kubernetes-cert)
         kubernetes_cert=$(opt_val "$2")
         shift 2
@@ -131,23 +142,24 @@ parse_args "$@"
 # todo validate args
 
 # debug
-echo "template_vmname=$template_vmname"
-echo "controller_hostname=$controller_hostname"
-echo "controller_ram=$controller_ram"
-echo "controller_cpus=$controller_cpus"
-echo "vboxdir=$vboxdir"
-echo "priv_key=$priv_key"
-echo "etcd_download=$etcd_download"
-echo "etcd_gzip=$etcd_gzip"
-echo "kube_apiserver_download=$kube_apiserver_download"
-echo "kube_apiserver_binary=$kube_apiserver_binary"
-echo "kube_controller_manager_download=$kube_controller_manager_download"
-echo "kube_controller_manager_binary=$kube_controller_manager_binary"
-echo "kubernetes_cert=$kubernetes_cert"
-echo "kubernetes_key=$kubernetes_key"
-echo "ca_cert=$ca_cert"
-echo "ca_key=$ca_key"
-exit
+#echo "template_vmname=$template_vmname"
+#echo "controller_hostname=$controller_hostname"
+#echo "controller_ram=$controller_ram"
+#echo "controller_cpus=$controller_cpus"
+#echo "vboxdir=$vboxdir"
+#echo "priv_key=$priv_key"
+#echo "etcd_download=$etcd_download"
+#echo "etcd_gzip=$etcd_gzip"
+#echo "kube_apiserver_download=$kube_apiserver_download"
+#echo "kube_apiserver_binary=$kube_apiserver_binary"
+#echo "kube_controller_manager_download=$kube_controller_manager_download"
+#echo "kube_controller_manager_binary=$kube_controller_manager_binary"
+#echo "kube_scheduler_download=$kube_scheduler_download"
+#echo "kube_scheduler_binary=$kube_scheduler_binary"
+#echo "kubernetes_cert=$kubernetes_cert"
+#echo "kubernetes_key=$kubernetes_key"
+#echo "ca_cert=$ca_cert"
+#echo "ca_key=$ca_key"
 
 run_count=$(VBoxManage list runningvms | awk '{print $1}' | grep -e'"'$controller_hostname'"' | wc -l)
 if [[ $run_count -eq 0 ]]; then
@@ -169,7 +181,7 @@ echo "Generating cluster TLS material into tls directory on this machine"
   --ca-key=$ca_key
 
 echo "Installing etcd into controller"
-etcd_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../control-plane/etcd" && pwd)"
+etcd_dir=$(realpath $script_dir/../control-plane/etcd)
 $etcd_dir/install-etcd\
  --priv-key=$priv_key\
  --controller-ip=$controller_ip\
@@ -181,8 +193,8 @@ $etcd_dir/install-etcd\
  --ca-cert=$ca_cert
 
 echo "Installing kube-apiserver into controller"
-kube_apiserver_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../control-plane/kube_apiserver" && pwd)"
-$kube_apiserver_dir/install-kube_apiserver\
+kube_apiserver_dir=$(realpath $script_dir/../control-plane/kube-apiserver)
+$kube_apiserver_dir/install-kube-apiserver\
  --priv-key=$priv_key\
  --controller-ip=$controller_ip\
  --controller-hostname=$controller_hostname\
@@ -193,22 +205,42 @@ $kube_apiserver_dir/install-kube_apiserver\
  --ca-cert=$ca_cert\
  --ca-key=$ca_key
 
-# kube-controller-manager
-kube_controller_manager_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../control-plane/kube_kube_controller_manager" && pwd)"
-"$script_dir"/install-kube_kube_controller_manager\
+echo "Installing kube-controller-manager into controller"
+kube_controller_manager_dir=$(realpath $script_dir/../control-plane/kube_kube_controller_manager)
+$kube_controller_manager_dir/install-kube-controller-manager\
  --priv-key=$priv_key\
  --controller-ip=$controller_ip\
  --controller-hostname=$controller_hostname\
- --kube-controller-manager-download=https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kube-controller-manager\
- --kube-controller-manager-binary=/home/eace/k8sbyhand/newroot/binaries\
- --kubernetes-cert=/home/eace/k8sbyhand/newroot/tls/kubernetes.pem\
- --kubernetes-key=/home/eace/k8sbyhand/newroot/tls/kubernetes-key.pem\
- --ca-cert=/home/eace/k8sbyhand/newroot/tls/ca.pem\
- --ca-key=/home/eace/k8sbyhand/newroot/tls/ca-key.pem
+ --kube-controller-manager-download=$kube_controller_manager_download\
+ --kube-controller-manager-binary=$kube_controller_manager_binary\
+ --kubernetes-cert=$kubernetes_cert\
+ --kubernetes-key=$kubernetes_key\
+ --ca-cert=$ca_cert\
+ --ca-key=$ca_key
 
-# kube-scheduler
+echo "Installing kube-scheduler into controller"
+kube_scheduler_dir=$(realpath $script_dir/../control-plane/kube-scheduler)
+$kube_scheduler_dir/install-kube-scheduler\
+ --priv-key=$priv_key\
+ --controller-ip=$controller_ip\
+ --controller-hostname=$controller_hostname\
+ --kube-scheduler-download=$kube_scheduler_download\
+ --kube-scheduler-binary=$kube_scheduler_binary\
+ --kubernetes-cert=$kubernetes_cert\
+ --kubernetes-key=$kubernetes_key\
+ --ca-cert=$ca_cert\
+ --ca-key=$ca_key
 
-# see /home/eace/k8sbyhand/control-plane/testing line 64 getting component statuses would be good
-# but requires admin kube config and maybe RBACs?
- 
-# stop the VM?
+# todo may need to retry for some period to allow time for everything to come up
+
+healthy_count=$(kubectl --kubeconfig=$kube_controller_manager_dir/kube-controller-manager.kubeconfig\
+ get componentstatuses --no-headers | awk '{print $2}' | grep Healthy | wc -l)
+
+if [[ "$healthy_count" -ne 3 ]]; then
+  echo "Unable to verify that controller was successfully configured"
+  exit 1
+fi
+
+echo "No errors detected with controller installation"
+
+# todo stop the VM or leave it running? probably running for worker install - but maybe a script arg
