Support control plane as static pods via --containerized-cplane arg

diff --git a/scripts/control-plane/etcd/install-etcd b/scripts/control-plane/etcd/install-etcd
--- a/scripts/control-plane/etcd/install-etcd
+++ b/scripts/control-plane/etcd/install-etcd
@@ -2,7 +2,8 @@
 
 set -e
 
-long_opts=priv-key:,controller-ip:,controller-hostname:,etcd-download:,etcd-gzip:,kubernetes-cert:,kubernetes-key:,ca-cert:
+long_opts=priv-key:,controller-ip:,controller-hostname:,etcd-download:,etcd-gzip:,kubernetes-cert:,kubernetes-key:,\
+containerized-cplane:,admin-kubeconfig:,ca-cert:
 script_name=$(basename "$0")
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
@@ -13,6 +14,8 @@ etcd_download=
 etcd_gzip=
 kubernetes_cert=
 kubernetes_key=
+containerize_cplane=0
+admin_kubeconfig=
 ca_cert=
 
 function opt_val() {
@@ -62,6 +65,14 @@ function parse_args() {
         kubernetes_key=$(opt_val "$2")
         shift 2
         ;;
+      --containerized-cplane)
+        containerized_cplane=$(opt_val "$2")
+        shift 2
+        ;;
+      --admin-kubeconfig)
+        admin_kubeconfig=$(opt_val "$2")
+        shift 2
+        ;;
       --ca-cert)
         ca_cert=$(opt_val "$2")
         shift 2
@@ -78,39 +89,43 @@ parse_args "$@"
 
 etcd_gzip_actual=$(xec make-download-path --download-url=$etcd_download --download-path=$etcd_gzip)
 subdir=$(basename -s .tar.gz $etcd_gzip_actual)
-
-# debug
-#echo "priv_key=$priv_key"
-#echo "controller_ip=$controller_ip"
-#echo "controller_hostname=$controller_hostname"
-#echo "etcd_download=$etcd_download"
-#echo "etcd_gzip=$etcd_gzip"
-#echo "etcd_gzip_actual=$etcd_gzip_actual"
-#echo "kubernetes_cert=$kubernetes_cert"
-#echo "kubernetes_key=$kubernetes_key"
-#echo "ca_cert=$ca_cert"
-
-xec download-obj --url="$etcd_download" --dest=$etcd_gzip_actual
-
-echo "extracting etcd binaries to controller"
-cat "$etcd_gzip_actual" | ssh -i $priv_key root@$controller_ip \
- "tar zxvf - --no-same-owner --strip-components 1 -C /usr/local/bin/ $subdir/etcd $subdir/etcdctl"
+etcd_pod_manifest=$script_dir/etcd-pod.yaml
 
 echo "copying etcd TLS material"
 ssh -i $priv_key root@$controller_ip "mkdir -p /etc/etcd /var/lib/etcd && chmod 700 /var/lib/etcd"
 scp -i $priv_key $kubernetes_cert $kubernetes_key $ca_cert root@$controller_ip:/etc/etcd
 
-echo "generating etcd service file"
-sed $script_dir/etcd.service\
- -e "s|ETCD_NAME|$controller_hostname|g" -e "s|INTERNAL_IP|$controller_ip|g"\
- | ssh -i $priv_key root@$controller_ip "cat > /etc/systemd/system/etcd.service"
+echo "extracting etcd binaries to controller"
+xec download-obj --url="$etcd_download" --dest=$etcd_gzip_actual
+cat "$etcd_gzip_actual" | ssh -i $priv_key root@$controller_ip \
+ "tar zxvf - --no-same-owner --strip-components 1 -C /usr/local/bin/ $subdir/etcd $subdir/etcdctl"
 
-echo "starting etcd service"
-ssh -i $priv_key root@$controller_ip "systemctl daemon-reload && systemctl enable etcd && systemctl start etcd"
+if [[ containerized_cplane -eq 0 ]]; then
+  echo "generating etcd service file"
+  sed $script_dir/etcd.service\
+   -e "s|ETCD_NAME|$controller_hostname|g" -e "s|INTERNAL_IP|$controller_ip|g"\
+   | ssh -i $priv_key root@$controller_ip "cat > /etc/systemd/system/etcd.service"
+  
+  echo "starting etcd service"
+  ssh -i $priv_key root@$controller_ip "systemctl daemon-reload && systemctl enable etcd && systemctl start etcd"
+else
+  echo "copying etcd static pod manifest to controller VM"
+  sed $etcd_pod_manifest\
+   -e "s|ETCD_NAME|$controller_hostname|g" -e "s|INTERNAL_IP|$controller_ip|g"\
+   | ssh -i $priv_key root@$controller_ip "cat > /etc/desktop-kubernetes/static-pods/etcd-pod.yaml"
+fi
 
 echo "verifying etcd is running"
-
-ssh -i $priv_key root@$controller_ip\
- "etcdctl --cert=/etc/etcd/kubernetes.pem --key=/etc/etcd/kubernetes-key.pem --cacert=/etc/etcd/ca.pem member list"
+  
+for i in {1..10}; do
+  if ssh -i $priv_key root@$controller_ip\
+    "etcdctl --cert=/etc/etcd/kubernetes.pem --key=/etc/etcd/kubernetes-key.pem --cacert=/etc/etcd/ca.pem member list"; then
+    break
+  elif [[ $i -eq 10 ]]; then
+    echo "Can't verify etcd installation"
+    exit 1
+  fi
+  sleep 10s
+done
 
 echo "no errors detected with etcd installation"
diff --git a/scripts/control-plane/kube-apiserver/install-kube-apiserver b/scripts/control-plane/kube-apiserver/install-kube-apiserver
--- a/scripts/control-plane/kube-apiserver/install-kube-apiserver
+++ b/scripts/control-plane/kube-apiserver/install-kube-apiserver
@@ -8,7 +8,8 @@
 
 set -e
 
-long_opts=priv-key:,controller-ip:,controller-hostname:,kube-apiserver-download:,kube-apiserver-binary:,kubernetes-cert:,kubernetes-key:,ca-cert:,ca-key:
+long_opts=priv-key:,controller-ip:,controller-hostname:,kube-apiserver-download:,kube-apiserver-binary:,kubernetes-cert:,kubernetes-key:,\
+containerized-cplane:,admin-kubeconfig:,ca-cert:,ca-key:
 script_name=$(basename "$0")
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
@@ -19,6 +20,8 @@ kube_apiserver_download=
 kube_apiserver_binary=
 kubernetes_cert=
 kubernetes_key=
+containerize_cplane=0
+admin_kubeconfig=
 ca_cert=
 ca_key=
 
@@ -69,6 +72,14 @@ function parse_args() {
         kubernetes_key=$(opt_val "$2")
         shift 2
         ;;
+      --containerized-cplane)
+        containerized_cplane=$(opt_val "$2")
+        shift 2
+        ;;
+      --admin-kubeconfig)
+        admin_kubeconfig=$(opt_val "$2")
+        shift 2
+        ;;
       --ca-cert)
         ca_cert=$(opt_val "$2")
         shift 2
@@ -90,23 +101,6 @@ parse_args "$@"
 kube_apiserver_binary_actual=$(xec make-download-path\
  --download-url=$kube_apiserver_download --download-path=$kube_apiserver_binary)
 
-# debug
-#echo "priv_key=$priv_key"
-#echo "controller_ip=$controller_ip"
-#echo "controller_hostname=$controller_hostname"
-#echo "kube_apiserver_download=$kube_apiserver_download"
-#echo "kube_apiserver_binary=$kube_apiserver_binary"
-#echo "kube_apiserver_binary_actual=$kube_apiserver_binary_actual"
-#echo "kubernetes_cert=$kubernetes_cert"
-#echo "kubernetes_key=$kubernetes_key"
-#echo "ca_cert=$ca_cert"
-#echo "ca_key=$ca_key"
-
-xec download-obj --url="$kube_apiserver_download" --dest="$kube_apiserver_binary_actual" --executable
-
-echo "copying kube-apiserver binary to controller"
-scp -i $priv_key $kube_apiserver_binary_actual root@$controller_ip:/usr/local/bin/kube-apiserver
-
 echo "generating TLS material for kube-apiserver"
 
 # gen some path refs to make the openssl commands below a little less busy looking
@@ -116,6 +110,7 @@ service_account_csr=$DTKBASE/generated/cert/service-account.csr
 aggregator_cert=$DTKBASE/generated/cert/aggregator.pem
 aggregator_key=$DTKBASE/generated/cert/aggregator-key.pem
 aggregator_csr=$DTKBASE/generated/cert/aggregator.csr
+kube_apiserver_pod_manifest=$script_dir/kube-apiserver-pod.yaml
 
 openssl req -nodes -newkey rsa:2048 -keyout $service_account_key -subj "/CN=service-accounts" -out $service_account_csr
 openssl x509 -req -days 10000 -in $service_account_csr -CA $ca_cert -CAkey $ca_key -CAcreateserial\
@@ -138,27 +133,56 @@ encryption_key=$(head -c 32 /dev/urandom | base64)
 sed $script_dir/encryption-config.yaml -e "s|ENCRYPTION_KEY|$encryption_key|g"\
  | ssh -i $priv_key root@$controller_ip "cat > /var/lib/kubernetes/encryption-config.yaml"
 
-echo "generating kube-apiserver service file"
-sed $script_dir/kube-apiserver.service -e "s|CONTROLLER_IP|$controller_ip|g"\
- | ssh -i $priv_key root@$controller_ip "cat > /etc/systemd/system/kube-apiserver.service"
+if [[ containerized_cplane -eq 0 ]]; then
+  xec download-obj --url="$kube_apiserver_download" --dest="$kube_apiserver_binary_actual" --executable
 
-echo "starting kube-apiserver service"
-ssh -i $priv_key root@$controller_ip\
- "systemctl daemon-reload && systemctl enable kube-apiserver && systemctl start kube-apiserver"
+  echo "copying kube-apiserver binary to controller"
+  scp -i $priv_key $kube_apiserver_binary_actual root@$controller_ip:/usr/local/bin/kube-apiserver
 
-echo "verifying kube-apiserver is running"
-set +e
-for i in {1..10}; do
-  http_code=$(curl -so /dev/null -w "%{http_code}" --cacert $ca_cert https://$controller_ip:6443/version)
-  if [[ "$http_code" == "200" ]]; then
-    break
+  echo "generating kube-apiserver service file"
+  sed $script_dir/kube-apiserver.service -e "s|CONTROLLER_IP|$controller_ip|g"\
+   | ssh -i $priv_key root@$controller_ip "cat > /etc/systemd/system/kube-apiserver.service"
+  
+  echo "starting kube-apiserver service"
+  ssh -i $priv_key root@$controller_ip\
+   "systemctl daemon-reload && systemctl enable kube-apiserver && systemctl start kube-apiserver"
+  
+  echo "verifying kube-apiserver is running"
+  set +e
+  for i in {1..10}; do
+    http_code=$(curl -so /dev/null -w "%{http_code}" --cacert $ca_cert https://$controller_ip:6443/version)
+    if [[ "$http_code" == "200" ]]; then
+      break
+    fi
+    sleep 1s
+  done
+  
+  if [[ "$http_code" != "200" ]]; then
+    echo "ERROR: Unable to verify kube-apiserver installation"
+    exit 1
   fi
-  sleep 1s
-done
-
-if [[ "$http_code" != "200" ]]; then
-  echo "ERROR: Unable to verify kube-apiserver installation"
-  exit 1
+else
+  echo "copying kube-apiserver static pod manifest to controller VM"
+  sed $kube_apiserver_pod_manifest -e "s|CONTROLLER_IP|$controller_ip|g"\
+   | ssh -i $priv_key root@$controller_ip "cat > /etc/desktop-kubernetes/static-pods/kube-apiserver-pod.yaml"
+  for i in {1..20}; do
+    if kubectl --kubeconfig $admin_kubeconfig -n kube-system wait pod\
+      -lcomponent=kube-apiserver --for=condition=ready --timeout=5s; then
+      break
+    elif [[ $i -eq 20 ]]; then
+      echo "Can't verify kube-apiserver installation"
+      exit 1
+    fi
+    sleep 5s
+  done
 fi
+
+echo "generating RBAC for kubelet authorization"
+
+# Per: https://kubernetes.io/docs/reference/access-authn-authz/kubelet-authn-authz/#kubelet-authorization
+# Snip: "...ensure the user identified by the --kubelet-client-certificate and --kubelet-client-key flags passed
+# to the apiserver is authorized..." etc. See 'CN = ' in 'gen-cluster-tls' script. Also see 'authorization.mode'
+# in 'scripts/worker/kubelet/kubelet-config.yaml'. All these configs together implement the guidance.
+kubectl --kubeconfig $admin_kubeconfig create -f $script_dir/rbac.yaml
 
 echo "no errors detected with kube-apiserver installation"
diff --git a/scripts/control-plane/kube-controller-manager/install-kube-controller-manager b/scripts/control-plane/kube-controller-manager/install-kube-controller-manager
--- a/scripts/control-plane/kube-controller-manager/install-kube-controller-manager
+++ b/scripts/control-plane/kube-controller-manager/install-kube-controller-manager
@@ -7,7 +7,8 @@
 set -e
 
 long_opts=priv-key:,controller-ip:,controller-hostname:,\
-kube-controller-manager-download:,kube-controller-manager-binary:,ca-cert:,ca-key:
+kube-controller-manager-download:,kube-controller-manager-binary:,\
+containerized-cplane:,admin-kubeconfig:,ca-cert:,ca-key:
 script_name=$(basename "$0")
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
@@ -16,6 +17,8 @@ controller_ip=
 controller_hostname=
 kube_controller_manager_download=
 kube_controller_manager_binary=
+containerize_cplane=0
+admin_kubeconfig=
 ca_cert=
 ca_key=
 
@@ -58,6 +61,14 @@ function parse_args() {
         kube_controller_manager_binary=$(opt_val "$2")
         shift 2
         ;;
+      --containerized-cplane)
+        containerized_cplane=$(opt_val "$2")
+        shift 2
+        ;;
+      --admin-kubeconfig)
+        admin_kubeconfig=$(opt_val "$2")
+        shift 2
+        ;;
       --ca-cert)
         ca_cert=$(opt_val "$2")
         shift 2
@@ -79,28 +90,13 @@ parse_args "$@"
 kube_controller_manager_binary_actual=$(xec make-download-path\
  --download-url=$kube_controller_manager_download --download-path=$kube_controller_manager_binary)
 
-# debug
-#echo "priv_key=$priv_key"
-#echo "controller_ip=$controller_ip"
-#echo "controller_hostname=$controller_hostname"
-#echo "kube_controller_manager_download=$kube_controller_manager_download"
-#echo "kube_controller_manager_binary=$kube_controller_manager_binary"
-#echo "kube_controller_manager_binary_actual=$kube_controller_manager_binary_actual"
-#echo "ca_cert=$ca_cert"
-#echo "ca_key=$ca_key"
-
-xec download-obj --url="$kube_controller_manager_download"\
- --dest="$kube_controller_manager_binary_actual" --executable
-
-echo "copying kube-controller-manager binary to controller VM"
-scp -i $priv_key $kube_controller_manager_binary_actual root@$controller_ip:/usr/local/bin/kube-controller-manager
-
 # gen some path refs to make the commands below a little less busy looking
 controller_mgr_cert=$DTKBASE/generated/cert/kube-controller-manager.pem
 controller_mgr_key=$DTKBASE/generated/cert/kube-controller-manager-key.pem
 controller_mgr_csr=$DTKBASE/generated/cert/kube-controller-manager.csr
 controller_mgr_kubeconfig=$DTKBASE/generated/kubeconfig/kube-controller-manager.kubeconfig
 controller_mgr_service=$script_dir/kube-controller-manager.service
+controller_mgr_pod_manifest=$script_dir/kube-controller-manager-pod.yaml
 
 echo "generating TLS material for kube-controller-manager"
 openssl req -newkey rsa:2048 -nodes -keyout $controller_mgr_key\
@@ -135,19 +131,39 @@ kubectl config use-context default --kubeconfig=$controller_mgr_kubeconfig
 echo "copying kube-controller-manager kubeconfig file to controller VM"
 scp -i $priv_key $controller_mgr_kubeconfig root@$controller_ip:/var/lib/kubernetes/
 
-echo "copying kube-controller-manager service file to controller VM"
-scp -i $priv_key $controller_mgr_service root@$controller_ip:/etc/systemd/system/
+if [[ containerized_cplane -eq 0 ]]; then
+  xec download-obj --url="$kube_controller_manager_download" --dest="$kube_controller_manager_binary_actual" --executable
 
-echo "starting kube-controller-manager service"
-ssh -i "$priv_key" root@$controller_ip\
- "systemctl daemon-reload && systemctl enable kube-controller-manager && systemctl start kube-controller-manager"
-exit
+  echo "copying kube-controller-manager binary to controller VM"
+  scp -i $priv_key $kube_controller_manager_binary_actual root@$controller_ip:/usr/local/bin/kube-controller-manager
 
-echo "verifying kube-controller-manager is running"
-set +e
-for i in {1..10}; do
-  ssh -i "$priv_key" root@$controller_ip "systemctl is-active --quiet kube-controller-manager" && break
-  sleep 1s
-done
+  echo "copying kube-controller-manager service file to controller VM"
+  scp -i $priv_key $controller_mgr_service root@$controller_ip:/etc/systemd/system/
+  
+  echo "starting kube-controller-manager service"
+  ssh -i "$priv_key" root@$controller_ip\
+   "systemctl daemon-reload && systemctl enable kube-controller-manager && systemctl start kube-controller-manager"
+  exit
+  
+  echo "verifying kube-controller-manager is running"
+  set +e
+  for i in {1..10}; do
+    ssh -i "$priv_key" root@$controller_ip "systemctl is-active --quiet kube-controller-manager" && break
+    sleep 1s
+  done
+else
+  echo "copying kube-controller-manager static pod manifest to controller VM"
+  scp -i $priv_key $controller_mgr_pod_manifest root@$controller_ip:/etc/desktop-kubernetes/static-pods/
+  for i in {1..20}; do
+    if kubectl --kubeconfig $admin_kubeconfig -n kube-system wait pod\
+      -lcomponent=kube-controller-manager --for=condition=ready --timeout=5s; then
+      break
+    elif [[ $i -eq 20 ]]; then
+      echo "Can't verify kube-scheduler installation"
+      exit 1
+    fi
+    sleep 5s
+  done
+fi
 
 echo "no errors detected with kube-controller-manager installation"
diff --git a/scripts/control-plane/kube-scheduler/install-kube-scheduler b/scripts/control-plane/kube-scheduler/install-kube-scheduler
--- a/scripts/control-plane/kube-scheduler/install-kube-scheduler
+++ b/scripts/control-plane/kube-scheduler/install-kube-scheduler
@@ -2,7 +2,8 @@
 
 set -e
 
-long_opts=priv-key:,controller-ip:,controller-hostname:,kube-scheduler-download:,kube-scheduler-binary:,ca-cert:,ca-key:
+long_opts=priv-key:,controller-ip:,controller-hostname:,kube-scheduler-download:,kube-scheduler-binary:,\
+containerized-cplane:,admin-kubeconfig:,ca-cert:,ca-key:
 script_name=$(basename "$0")
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
@@ -11,6 +12,8 @@ controller_ip=
 controller_hostname=
 kube_scheduler_download=
 kube_scheduler_binary=
+containerize_cplane=0
+admin_kubeconfig=
 ca_cert=
 ca_key=
 
@@ -53,6 +56,14 @@ function parse_args() {
         kube_scheduler_binary=$(opt_val "$2")
         shift 2
         ;;
+      --containerized-cplane)
+        containerized_cplane=$(opt_val "$2")
+        shift 2
+        ;;
+      --admin-kubeconfig)
+        admin_kubeconfig=$(opt_val "$2")
+        shift 2
+        ;;
       --ca-cert)
         ca_cert=$(opt_val "$2")
         shift 2
@@ -74,21 +85,6 @@ parse_args "$@"
 kube_scheduler_binary_actual=$(xec make-download-path\
  --download-url=$kube_scheduler_download --download-path=$kube_scheduler_binary)
 
-# debug
-#echo "priv_key=$priv_key"
-#echo "controller_ip=$controller_ip"
-#echo "controller_hostname=$controller_hostname"
-#echo "kube_scheduler_download=$kube_scheduler_download"
-#echo "kube_scheduler_binary=$kube_scheduler_binary"
-#echo "kube_scheduler_binary_actual=$kube_scheduler_binary_actual"
-#echo "ca_cert=$ca_cert"
-#echo "ca_key=$ca_key"
-
-xec download-obj --url="$kube_scheduler_download" --dest="$kube_scheduler_binary_actual" --executable
-
-echo "copying kube-scheduler binary to controller VM"
-scp -i $priv_key $kube_scheduler_binary_actual root@$controller_ip:/usr/local/bin/kube-scheduler
-
 # gen some path refs to make the commands below a little less busy looking
 kube_scheduler_cert=$DTKBASE/generated/cert/kube-scheduler.pem
 kube_scheduler_key=$DTKBASE/generated/cert/kube-scheduler-key.pem
@@ -96,6 +92,7 @@ kube_scheduler_csr=$DTKBASE/generated/cert/kube-scheduler.csr
 kube_scheduler_kubeconfig=$DTKBASE/generated/kubeconfig/kube-scheduler.kubeconfig
 kube_scheduler_service=$script_dir/kube-scheduler.service
 kube_scheduler_yaml=$script_dir/kube-scheduler.yaml
+kube_scheduler_pod_manifest=$script_dir/kube-scheduler-pod.yaml
 
 echo "generating TLS material for kube-scheduler"
 openssl req -newkey rsa:2048 -nodes -keyout $kube_scheduler_key\
@@ -127,22 +124,42 @@ kubectl config set-context default \
 kubectl config use-context default --kubeconfig=$kube_scheduler_kubeconfig
 
 echo "copying configuration files to controller VM"
-ssh -i "$priv_key" root@$controller_ip "mkdir -p /var/lib/kubernetes /etc/kubernetes/config"
+ssh -i $priv_key root@$controller_ip "mkdir -p /var/lib/kubernetes /etc/kubernetes/config"
 scp -i $priv_key $kube_scheduler_kubeconfig root@$controller_ip:/var/lib/kubernetes/
 scp -i $priv_key $kube_scheduler_yaml root@$controller_ip:/etc/kubernetes/config/
 
-echo "copying kube-scheduler service file to controller VM"
-scp -i $priv_key $kube_scheduler_service root@$controller_ip:/etc/systemd/system/
+if [[ containerized_cplane -eq 0 ]]; then
+  xec download-obj --url="$kube_scheduler_download" --dest="$kube_scheduler_binary_actual" --executable
 
-echo "starting kube-scheduler service"
-ssh -i "$priv_key" root@$controller_ip\
- "systemctl daemon-reload && systemctl enable kube-scheduler && systemctl start kube-scheduler"
+  echo "copying kube-scheduler binary to controller VM"
+  scp -i $priv_key $kube_scheduler_binary_actual root@$controller_ip:/usr/local/bin/kube-scheduler
 
-echo "verifying kube-scheduler is running"
-set +e
-for i in {1..10}; do
-  ssh -i "$priv_key" root@$controller_ip "systemctl is-active --quiet kube-scheduler" && break
-  sleep 1s
-done
+  echo "copying kube-scheduler service file to controller VM"
+  scp -i $priv_key $kube_scheduler_service root@$controller_ip:/etc/systemd/system/
+
+  echo "starting kube-scheduler service"
+  ssh -i $priv_key root@$controller_ip\
+   "systemctl daemon-reload && systemctl enable kube-scheduler && systemctl start kube-scheduler"
+
+  echo "verifying kube-scheduler is running"
+  set +e
+  for i in {1..10}; do
+    ssh -i $priv_key root@$controller_ip "systemctl is-active --quiet kube-scheduler" && break
+    sleep 1s
+  done
+else
+  echo "copying kube-scheduler static pod manifest to controller VM"
+  scp -i $priv_key $kube_scheduler_pod_manifest root@$controller_ip:/etc/desktop-kubernetes/static-pods/
+  for i in {1..20}; do
+    if kubectl --kubeconfig $admin_kubeconfig -n kube-system wait pod\
+      -lcomponent=kube-scheduler --for=condition=ready --timeout=5s; then
+      break
+    elif [[ $i -eq 20 ]]; then
+      echo "Can't verify kube-scheduler installation"
+      exit 1
+    fi
+    sleep 5s
+  done
+fi
 
 echo "no errors detected with kube-scheduler installation"
